### ISSUE TITLE
Kind request to hide package from Atmosphere?

### ISSUE THREAD

**Issue by dandv** [CulturalMe/meteor-reactive-publish#2]
Hi @CulturalMe / @edgee,

Looks like you haven't had time to devote to this package, and a lot of [actively developed alternatives have emerged](https://hackpad.com/Meteor-reactive-join-publication-packages-MpSFfsZrMxa).

Could you do the community a favor and hide this package from Atmosphere searches, while still keeping it installable by apps and dependencies?

All you need to do is run 

```
meteor admin set-unmigrated edgee:meteor-reactive-publish
```

Thanks for helping keep a clean Atmosphere,
Dan

**Comment by gsuess** [comment]
done
